meta_product_name: "Pet Family"
meta_title: "Pet family - Organize a sua rotina!"
meta_description: "Promova a maior integração de sua família através da plataforma de gerenciamento das atividades e rotinas do seu pet. É saúde e bem-estar para todos!"
meta_image: "pet_family.site.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
